# Generated by Django 4.1.7 on 2023-03-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_consuming', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consume',
            old_name='food',
            new_name='food_consumed',
        ),
    ]
